name: continuous integration

on:
  - push
  - pull_request

jobs:
#  cancel-previous:
#    runs-on: ubuntu-latest
#    if: github.ref != 'refs/heads/main'
#    steps:
#      - uses: khan/pull-request-workflow-cancel@1.0.0
#        with:
#          workflows: "main.yml"
#        env:
#          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  formatting:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Check formatting
        run: mvn com.coveo:fmt-maven-plugin:check -Dverbose=true
      - name: Comment PR
        if: github.event_name == 'pull_request' && failure()
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          message: 'Please format your code with `mvn com.coveo:fmt-maven-plugin:format`.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  testing:
    runs-on: ubuntu-latest
    needs: formatting
    strategy:
      matrix:
        java: ['8', '11', '16']
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean test
